name: motivegold
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  convex_bottom_bar: ^3.2.0
  get: ^4.6.5
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.18.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  progress_dialog_null_safe: ^1.0.7
  awesome_dialog: ^3.1.0
  image_picker: ^1.0.4
  settings_ui: ^2.0.2
  location: ^5.0.3
  select_dialog: ^2.0.1
  easy_localization: ^3.0.0

  getwidget: ^4.0.0
  ripple_button: ^3.4.1
  flutter_fast_forms: ^13.0.0

  cool_stepper_reloaded: ^3.2.6
  flutter_secure_storage: ^8.0.0

  data_table_2: ^2.5.9
  flutter_slidable: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  babstrap_settings_screen: ^0.1.6
  package_info_plus: ^4.0.2
  url_launcher: ^6.0.20
  about: ^2.1.3
  animate_do: ^3.1.2
  flutter_svg: ^2.0.9

  flutter_modal_dialog: ^0.0.4
  loading_indicator: ^3.1.1
  easy_sidemenu: ^0.5.0
  font_awesome_flutter: ^10.7.0
  badges: ^3.1.2
  empty_widget: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon2.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flags/
    - assets/locale/
    - assets/icons/
    - assets/icons/gold/

  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Regular.ttf
          weight: 100

