name: motivegold
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  convex_bottom_bar: ^3.2.0
  get: ^4.6.5
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.20.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  progress_dialog_null_safe: ^3.0.0
  awesome_dialog: ^3.1.0
  image_picker: ^1.0.7
  settings_ui: ^2.0.2
  location: ^6.0.2
  easy_localization: ^3.0.7+1

  getwidget: ^6.0.0
  #flutter_fast_forms: ^17.1.0

  cool_stepper_reloaded: ^3.2.6
  flutter_secure_storage: ^9.2.4

  data_table_2: ^2.5.9
  flutter_slidable: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  babstrap_settings_screen: ^0.1.7
#    path: ./plugins/babstrap_settings_screen
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  url_launcher: ^6.0.20
  about: ^2.1.3
  animate_do: ^3.1.2
  flutter_svg: ^2.0.9

  flutter_modal_dialog: ^0.0.4
  dialogx: ^1.0.0
  loading_indicator: ^3.1.1
  easy_sidemenu: #^0.6.1
    path: ./plugins/easy_sidemenu
  font_awesome_flutter: ^10.7.0
  badges: ^3.1.2
  empty_widget_fork: ^0.0.6
#  pattern_formatter: ^4.0.0
  pdf: ^3.11.3
  printing: ^5.14.0
  thai_idcard_reader_flutter: ^0.0.7
  mirai_dropdown_menu: ^0.0.8+2
  substring_highlight: ^1.0.33
  board_datetime_picker: ^2.2.1
  quiver: ^3.2.1
  flutter_to_pdf: ^0.2.0
  masked_text: ^1.1.2
  cached_network_image: ^3.4.1
  lottie: ^3.1.2
  flutter_simple_calculator:
    path: ./plugins/simple_calculator
  math_expressions: ^2.3.0
  table_desk: ^0.0.1
  dropdown_button2: ^3.0.0-beta.19
  mobile_device_identifier: ^0.0.3
  jiffy: ^6.3.2
  rename_app: ^1.6.3
  rename: ^3.1.0
  syncfusion_flutter_datepicker: ^29.2.10
  sizer: ^3.0.5
  file_picker: ^10.2.0
  shared_preferences: ^2.5.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon2.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flags/
    - assets/locale/
    - assets/icons/
    - assets/icons/gold/
    - assets/fonts/PrintAble4U/
    - assets/fonts/thai/

  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Regular.ttf
          weight: 100

